### PR TITLE
reformats changelog file

### PR DESCRIPTION
**Pull request by agzam**
reformats changelog file, adds newly added items

### CODE REVIEW

**Comment by Grazfather** [comment]
Why not use https://keepachangelog.com/en/1.0.0/?

**Comment by agzam** [comment]
Right, that's why I made a draft PR. Initially I wanted it to keep in Org format, but I think Markdown makes a better sense here. Can't force everyone to use Emacs :)

See if it looks better now

**Comment by Grazfather** [comment]
I don't care if it's still in org format, tbf, but headings for version, with added, fixed, and changed sub headings is a good structure to follow.

That said, I know that github has trouble properly rendering some org (e.g. `="bla"=`) doesn't render properly for some reason, so maybe Markdown is just easier.

**Comment by agzam** [comment]
Well, we don't follow semver since we don't have "versions". The one and only "release" we had was back when Jay revamped the state-machine. But Added/Changed subsections, I like that.

Also, I think I'm gonna convert it back to Org. It's a bit more convenient for me personally. Inserting dates, links, etc., much  simpler.

**Comment by Grazfather** [comment]
That sounds great to me.

**Comment by Grazfather** [comment]
Might be worth adding to CONTRIBUTING or a PR template an ask that contributors add their own change to the changelog.

**Review by Grazfather — APPROVED** [review]

**Pull request merged**
