### PR TITLE
Refactor modals, configuration, and app specific behaviors

### PR DESCRIPTION
**Pull request by eccentric-j**
Hi @agzam, I have completed my refactoring to support some of those features we discussed:
- Centralized menus, key bindings, and app configurations into config.fnl
- Refactored modal, apps, and keybinding behaviors.
- Refactored vim mode
- Created a new statemachine lib which is used by modal, apps, and vim mode.
- Setup support for `~/.hammerspoon/private/` and `~/.hammerspoon/private/config.fnl` to safely override defaults with files you can easily symlink to your dotfiles.

Please let me know what you think.

### CODE REVIEW

**Comment by agzam** [comment]
Oh wow, this is amazing. I'll try to review it this weekend. Please allow me some time, having full-time job makes it challenging.
Can't appreciate you enough though, thank you!

**Comment by eccentric-j** [comment]
@agzam Thanks! There's definitely no rush so please take your time. It's a great project and was a blast to hack on.

**Comment by agzam** [comment]
@eccentric-j I finally was able to try this branch. It's amazing. This is a tremendous amount of work and lots of improvements. However, I don't think we would be able to merge it as is (even after resolving conflicts). But I don't want to reject this work either (or force you to split it into smaller units), it is extremely valuable, and probably this is the next evolutionary step for this project, to lift it from being "a toy" into a helpful tool that might be useful for many people.

Here's my proposal. Let's merge this into a `develop` branch, and then sketch a plan to make a "release" at some point.

There are a few things I would like to improve:

- Documentation. I want to improve the rationale and describe the structure of the project. Add wiki, FAQ, etc. Add docstrings as headers to modules and functions. e.g.: `atom` makes sense to me since I'm familiar with Clojure, for those who are not - it will be confusing, they might think it has something to do with the editor. 

- It seems this PR breaks the "local-modals" feature. i.e.: similar to major mode bindings in Emacs, I thought every app could have its own local-modal, this is probably not a huge deal, since you pushed your work while I was still experimenting with this feature. Maybe we can think of better way of implementing app local modals.

- Further 'customizability.' e.g., it makes sense for 'Spotify' to be a default player, but we should make it possible to set it maybe from the UI. Perhaps even allow setting multiple player apps.

- Vim module is fantastic, but it feels it needs to be polished. e.g., Pressing ESC in `Normal` mode shouldn't disable it, it should stay in 'Normal' mode. Also, the mode indicator maybe could be even more unobtrusive.

- I love the new panel. I thought at some point to build it at the bottom of the screen (similar to which-key panel in Emacs) but never got to experiment with it, your improvements are lovely already. I tried changing the dots and replaced them with `∙` (bullet operator), but at the end using nothing but spaces IMO made it look much cleaner.
  Here's another idea: maybe we can slightly change the background-color gradient at different levels of the menu. I don't know, just a thought.

Overall, I love this work, and I'll continue exploring these improvements. Thank you for this incredible work!

**Comment by agzam** [comment]
I changed the base of this PR. Let's resolve conflicts and merge it, then after that point I am not going to push anything to either `develop` or `master` without a PR.

**Comment by agzam** [comment]
@eccentric-j, btw: J and K in browser-keys are in the wrong order. They should follow the same pattern that Vimium Chrome-extention uses: `Shift+j` to go to left, `Shift+k` to go to the right tab.

**Comment by eccentric-j** [comment]
Thanks @agzam!

I'm with you on those changes and merging into the develop branch first.

- Fixed the browser bindings so that J & K navigate in the correct order.
- Disabled the binding to disable VIM mode when you press ESC in normal.
- Local, app-specific menu items are now listed at the bottom of the main menu.
- Replaced the `"."` character in menu item separators with spaces `" "`.
 
What is broken in local modals exactly? Currently, you can specify custom menus and key bindings to any app you want. In my latest pushes, the app-specific menu items are listed below the main menu items. This is in config.fnl with less than 3 lines of code by concat'ing the local items to the main menu `menu-items`. 

As for music customization, I think we should leave that up to users. For instance, in my private config I didn't like using the media keys as chrome seems to be blocking those from reaching Spotify.

```
(local media-items
       [return
        {:key :s
         :title "Play or Pause"
         :action hs.spotify.playpause}
        {:key :h
         :title "Prev Track"
         :action hs.spotify.previous}
        {:key :l
         :title "Next Track"
         :action hs.spotify.next}
        {:key :j
         :title "Volume Down"
         :action "multimedia:volume-down"
         :repeatable true}
        {:key :k
         :title "Volume Up"
         :action "multimedia:volume-up"
         :repeatable true}
        {:key :a
         :title (.. "Launch " music-app)
         :action (activator music-app)}])
```

Can you please describe how you wanted app-specific modals to work in more detail in case I'm still missing the mark?

Lastly, do you want me to fix those issues in this branch? Or should I merge into your develop and make PRs for more docs, vim refinements, and further customizations?

**Comment by agzam** [comment]
Cool. Let's now create smaller, focused PRs aimed at `develop`.

**Pull request merged**
