### PR TITLE
Switches default bindings to use the option (alt) key instead of cmd

### PR DESCRIPTION
**Pull request by eccentric-j**
- Opening the menu is `alt + space`
- Switching to the previous app is `alt + p`
- Switching to the next app is `alt + n`

Attempts to fix agzam/spacehammer#30

### CODE REVIEW

**Comment by agzam** [comment]
@eccentric-j I pushed some changes to the readme and also changed tab-switcher modifier to `Alt`. I will continue reviewing readme. I think this would be our last PR before we release development.

Question, just to make sure: we don't have to change anything else, right? Changing mods in ~/.hammerspoon/config.fnl would also change it for ~/.spacehammer/config.el (for users who don't have it yet), right?

**Comment by eccentric-j** [comment]
@agzam Those changes make sense so far. I'm ready to get this released! 🚀 

You are correct about the config. Just modify the ~/.spacehammer/config.fnl in this repo and it will be copied to ~/.spacehammer/config.fnl for all new users.

**Comment by agzam** [comment]
@eccentric-j can you please take a look at the last few commits I made here, then If you are okay with those, I will merge this to `develop`. And if neither of us catch anything and there are no "last minute fixes", I will tag and release a new version.

**Comment by eccentric-j** [comment]
The changes to the README.md look good to me. Merge and release when you're up for it! 🎉 🚀

**Pull request merged**
