### PR TITLE
repl prototype

### PR DESCRIPTION
**Pull request by eccentric-j**
Creates a nREPL server using jeejah. This feature is not done but the base of this can be used to deliver a more polished feature.

### CODE REVIEW

**Comment by martinklepsch** [comment]
I also started looking into this (see linked issue above). I'm currently stuck at actually connecting to the REPL server that is started inside hammerspoon (or any jeejah nREPL server for that matter). 

Do you have any pointers how to test if the jeejah server is running correctly and how to evaluate stuff via that connection? I tried 

- [shevek](https://git.sr.ht/~technomancy/shevek), seems to be able to evaluate `(print "test")` but fails with `(+ 1 2)`
- [rep](https://github.com/eraserhd/rep)` resulting in `java.net.ConnectException: Connection refused`
-  and the bare bones [`clj`](https://nrepl.org/nrepl/usage/clients.html#_using_the_built_in_client) with the same `Connection refused` error

**Comment by agzam** [comment]
@martinklepsch  I only did some simple experiments, I need to find some time to play with it some more. When I was fooling around with Jeeja, I was able to connect to it using https://github.com/sanel/monroe from Emacs.

**Comment by Grazfather** [comment]
I'm playing with this.

To get it to work with Lua 5.4 I had to make a custom `serpent` and `jeejah`

I clone serpent, checkout 0.30 and make a custom rockspec:

```lua
$ \cat misc/serpent-0.30-1.rockspec
package = "serpent"
version = "0.30-1"
source = {
  url = "git://github.com/pkulchenko/serpent.git",
  tag = "0.30"
}

description = {
  summary = "Lua serializer and pretty printer",
  homepage = "https://github.com/pkulchenko/serpent",
  maintainer = "Paul Kulchenko <paul@kulchenko.com>",
  license = "MIT",
}

dependencies = {
  "lua >= 5.1",
}

build = {
  type = "builtin",
  modules = {
    ["serpent"] = "src/serpent.lua",
  },
  copy_directories = { "t" },
}
```

then install it

```bash
luarocks make misc/serpent-0.30-1.rockspec
```

In jeejah I made another custom rockspec

```lua
-- -*- lua -*-

package = "jeejah"
version = "0.3.1-5"
source = {
   url = "git+https://gitlab.com/technomancy/jeejah.git",
   tag = "0.3.1",
}
description = {
   summary = "An nREPL server",
   detailed = [[
        Implements a server that speaks the nREPL protocol and allows
        clients to connect and evaluate code over a network connection.
    ]],
   homepage = "https://gitlab.com/technomancy/jeejah",
   license = "MIT/X11",
}
dependencies = {
   "lua >= 5.1",
   "luasocket = 3.0rc1-2",
   "serpent = 0.30-1",
}
build = {
   type = "builtin",
   modules = { jeejah = "jeejah.lua",
               ["jeejah.fenneleval"] = "jeejah/fenneleval.lua",
               bencode = "bencode.lua",
   },
   install = { bin = { "bin/jeejah" } },
}
```

It's only different that I require `serpent` 0.30-1, which doesn't exist.

I then install it

```bash
luarocks make rockspecs/jeejah-0.3.1-5.rockspec
```

In core.fnl:

```lisp
(require "coroutine")

(global repl-coro (repl.start))
(global repl-coro-freq 0.05)
(fn repl-spin []
  (coroutine.resume repl-coro)
  (when (not= (coroutine.status repl-coro)
              "dead")
    (hs.timer.doAfter repl-coro-freq repl-spin)))
(global repl-timer (hs.timer.doAfter repl-coro-freq repl-spin))
```

which is mostly cribbed from https://github.com/Hammerspoon/hammerspoon/issues/2377#issuecomment-687708178

I then use `shevek` as the client.

**Comment by eccentric-j** [comment]
Very nice! I think it might be worth making an upstream PR to serpent to see what happens, if you haven't tried that already.

Looks like an upstream PR for https://gitlab.com/technomancy/jeejah/-/issues/8 was created so interested to see how that will be handled. My guess is the author will suggest a patch for accepting a function to provide a bencode implementation, but maybe they'll have another idea in mind.

**Comment by Grazfather** [comment]
Considering 0.30 still isn't on lua rocks and that there's a 2 year old [ticket](https://github.com/pkulchenko/serpent/issues/33) about it I am not hopeful that we'll see anything there.

**Pull request closed without merging**
